### ISSUE TITLE
Support Emacs versions

### ISSUE THREAD

**Issue by zonuexe** [sunrise-commander/sunrise-commander#67]
This package has a dependency on Emacs 22 and 23. They are too old today. I want to have a dependency on Emacs 26 (released in 2016) and `cl-lib` 0.5.

Do you have any opinion?

**Comment by lassik** [comment]
I don't have an informed opinion as I don't know what the SC userbase is running. SC is geared toward experienced users so I'd imagine most have a very recent Emacs, but that's just a guess. Some people may be using it at a corporate job where they need to use an old Linux distro :)

Here are some data points:

* According to the [list of Emacs release dates](https://www.gnu.org/savannah-checkouts/gnu/emacs/history.html):
  * Emacs 23 is ten years old.
  * Emacs 24 is seven years old
  * Emacs 25 is three years old
  * Emacs 26 is one year old.
* Minimum requirements for popular MELPA packages:
  * web-mode: Emacs 23.1
  * flycheck: Emacs 24.3
  * company: Emacs 24.3
  * projectile: Emacs 25.1
* I've personally maintained and contributed to many packages that require `((emacs "24") (cl-lib "0.5"))` and haven't had any complaints about those requirements.

Since SC is for experienced users and Emacs 24 is already seven years old (!), I suggest we raise the minimum requirements to `((emacs "24") (cl-lib "0.5"))` right away.

We can also discuss increasing them to more recent versions. Do you have specific features you'd like that were introduced in Emacs 25 or 26?

**Comment by lassik** [comment]
Perhaps the best data point: the [Repology list of default Emacs versions](https://repology.org/project/emacs/versions) for many package managers. According to that list, Emacs 24 covers just about everything except the oldest long-term support releases. Emacs 25 covers about all the normal stable releases.

**Comment by zonuexe** [comment]
[package-lint](https://github.com/purcell/package-lint/blob/master/package-lint.el#L83) package has a list of added functions for each version.  In my experience, I find it easier to work with emacs 24.3 or higher.  It has the `user-local` function and the` setq-local` `defvar-local` macro.

However, for the time being I agree to have dependencies on `(emacs “24”)` and `(cl-lib “0.5”)`.

**Comment by lassik** [comment]
Emacs 24.1 is the first release to support `lexical-binding`. The SC codebase already has `-*- lexical-binding: t -*-` declarations. That means the actual requirement is already Emacs 24 and the `Compatibility: GNU Emacs 22+` and `23+` comments are out of date. (Assuming some of the code actually depends on lexical binding. I think we should depend on it - dynamic binding is basically asking for bugs in complex situations.)

**Comment by lassik** [comment]
> [package-lint](https://github.com/purcell/package-lint/blob/master/package-lint.el#L83) package has a list of added functions for each version.

Cool. I didn't know that and I've even sent PRs to package-lint :D

> In my experience, I find it easier to work with emacs 24.3 or higher. It has the `user-local` function and the `setq-local` `defvar-local` macro.

I agree that those are useful.

From the quick MELPA survey above, flycheck and company depend on Emacs 24.3. From Repology, all of the distros that ship 24.x have 24.3 or higher. So it should be completely safe to depend on 24.3.

**Comment by lassik** [comment]
OK, with @zonuexe 's PR the minimum requirements are now `((emacs "24.3") (cl-lib "0.5"))`. I'm closing the issue. If there are any new concerns later, feel free to comment and I'll re-open it.
