### ISSUE TITLE
Rebuild the extension mechanism

### ISSUE THREAD

**Issue by zonuexe** [sunrise-commander/sunrise-commander#77]
refs #76 

In the current architecture, each sunrise extension has side effects only when the file is loaded. These provide functions for unloading, but the operation of switching between enable and disable is complicated. And that is not modern.

They can be replaced with either functions (hook) or minor mode.

**Comment by lassik** [comment]
You are much better qualified to make this decision than I am.

It might be nice for users if there are `customize` variables for turning extensions on and off. Would this be significantly more difficult to implement than just using minor modes?

**Comment by lassik** [comment]
`grep -n '^(require' *.el` shows that some of the extensions (`sunrise-*.el`) require Emacs packages that are not required by the main `sunrise.el`. This situation would be easiest to handle if we submit each extension to MELPA as its own package. All of those would have a dependency on the main `sunrise` package.

Once the extensions are installed, how to turn them on and off is a different question. It would be easiest to have them always on (so that once you have installed an extension, you can only turn it off by uninstalling it). Or they could be minor modes or `customize` variables. @zonuexe you are better qualified to make this decision than I am.

**Comment by lassik** [comment]
@zonuexe Should we start with the simplest thing, and have each extension be always on if that extension's package has been required? We can later add a fancier way to turn extensions on/off at runtime. But we'd get SC to MELPA faster if we start with the simplest thing that works. And it's probably good enough for most users.

Currently each extension ends with:

`;;;###autoload (eval-after-load 'sunrise '(sunrise-extend-with 'sunrise-w32))`

But `sunrise-extend-with` only does:

(defun sunrise-extend-with (extension &optional filename)
  "..."
  (when sunrise-autoload-extensions
    (require extension filename t)))

I submitted a new PR #99 which is an extended version of your old PR #76 to do this.

**Comment by lassik** [comment]
Merged #99. We can re-open this issue later if changes are needed.
